/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("com.squareup.okio:okio:3.16.0")
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass = "MainKt"
}
